import type { Metadata } from "next";
import Navbar from "@/components/navbar/navbar";
import { getDictionary, hasLocale } from "@dictionary";
import { notFound } from "next/navigation";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: 'fr' }, { lang: 'en' }];
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;

  // Vérifier que la langue existe, sinon 404
  if (!hasLocale(lang)) {
    notFound();
  }

  const dict = await getDictionary(lang);

  return (
    <html lang={lang}>
      <body className="antialiased">
        <Navbar dict={dict}/>
        {children}
      </body>
    </html>
  );
}
